[variables]
NIXPACKS_PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip"]

[phases.build]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn app.api:app --host 0.0.0.0 --port $PORT"
