[variables]
PYTHON_VERSION = "3.10"

[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev"]

[phases.install]
onlyIncludeFiles = ["requirements.txt"]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn app.api:app --host 0.0.0.0 --port $PORT"
