[phases.setup]
nixPkgs = ['gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip setuptools wheel']

[phases.build]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'uvicorn app.api:app --host 0.0.0.0 --port $PORT'
