services:
  - type: web
    name: iris-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: https://aufuhhidcwyjtpafwckk.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1ZnVoaGlkY3d5anRwYWZ3Y2trIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTI3OTA1OCwiZXhwIjoyMDcwODU1MDU4fQ.8wJnLqjdQ_kxQNTc6uIo8eVvV_r9K3QpjOIYLM2C7Uk
      - key: BUCKET_NAME
        value: images
